title: Janosch Korell # your name (or website title) here
logo: "/images/Janosch Korell klein.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data Scientist with 4+ years experience as a freelancer (Musician,Bandleader), organiser, teacher and founder of several bands with a 
 Bachelor's degree in Politics/Social Sciences and quantitative focus and statistics. 
  <br><br>
 Focus: NLP, "classical" statistics, causality/inference and text mining.
  <br><br>
  I currently own a collaboration with https://www.hanseatic-statistics.de.
  <br><br>
  <a href="https://www.linkedin.com/in/janosch-korell-b2a1a3226/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
